### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by zymex22** [juanosarg/GeneticRim#5]
Hello
may i suggest using collapse/dropdown on those 4 rugs in furniture
they take up alot of space, in a modded rimworld =) 

im trying to clean my rimworld up, and try help mod makers to do same, KV already done it on he's fridges save up 3 slots from temperature, and i have done it in my mods too where items are not stuffed.

	
Use this in top inside your def, to create dropdown menu
```
<DesignatorDropdownGroupDef>
		<defName>Drowdown_name_here</defName>
	</DesignatorDropdownGroupDef>

```
use this in base/parent or in each sub.
`<designatorDropdown>Drowdown_name_here</designatorDropdown>`

can also be used in your genpod+adv. gene pod or other places with no stuffed.
but at least in those categories that are in shared menus =)

**Comment by juanosarg** [comment]
I'll probably just move the rugs to the Genetic category, since I don't like to hide them behind a dropdown. Many users won't ever know they are there
